### ISSUE TITLE
Search parameter 'modifiedFrom' does not work

### ISSUE THREAD

**Issue by marijorg** [Geta/service-api#47]
The modifiedFrom parameter is parsed as null, hence ignored as search parameter. 
Solution: change parameter type from dateTime to string in the SearchOrdersRequest class.

**Comment by marisks** [comment]
Date parameters should not be as string parameters. Should fix it properly.

**Comment by frederikvig** [comment]
Agree, issue with model binding which should be fixed. @marisks could you take a look on Wednesday?

**Comment by marisks** [comment]
Checked this and binding works properly.

The issue is with Swagger - it documents parameters wrongly. Will check why it does that.

**Comment by marisks** [comment]
Seems that it is quite common issue: https://github.com/domaindrivendev/Swashbuckle/issues/515

And there is a fix which I will apply.
